### ISSUE TITLE
[Feature Request] Project custom content inside <ngx-scrolltop> component using <ng-content>

### ISSUE THREAD

**Issue by lpikora** [bartholomej/ngx-scrolltop#1]
It would be great using custom component inside <ngx-scrolltop></ngx-scrolltop> like:

```
<ngx-scrolltop>
  <my-custom-button-component></my-custom-button-component>
</ngx-scrolltop>
```

It will allow perfectly customise scroll top button.

**Comment by bartholomej** [comment]
@lpikora Check this out ;) https://github.com/bartholomej/ngx-scrolltop/releases/tag/v2.0.0
