### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by ericrovtar** [bartholomej/ngx-scrolltop#100]
@bartholomej Me again. :)

I saw you updated the package version to 18, but it looks like the peer dependencies are set to be `<18`. Is there any chance to get these updated to include Angular 18?

Thanks!

**Comment by ericrovtar** [comment]
Just wanted to check in on this. I believe all that has to be updated is to include Angular 18 as the peer dependency in `package.json`:

`"peerDependencies": {
    "@angular/common": ">=16 <=18",
    "@angular/core": ">=16 <=18"
  },`

I tried pushing a PR with this change for you, but it won't let me.

**Comment by bartholomej** [comment]
Hi @ericrovtar
Thx for your suggestion.

Fixed in v18.0.1

Let me know ;)

**Comment by ericrovtar** [comment]
@bartholomej Works like a charm! Thanks. :)
