### ISSUE TITLE
Scroll to top icon not appearing in on iphone 6.

### ISSUE THREAD

**Issue by SovietFarmer** [bartholomej/ngx-scrolltop#12]
Apologies, I don't have any more devices to test on than iphone 5C (IOS version 10.3.3) but it works on IOS 14, below is my configuration of my app.component.html in my Angular 10 app.

```<app-header></app-header>
<router-outlet></router-outlet>
<ngx-scrolltop
  [size]="50"
  backgroundColor="#2E5299"
  symbolColor="#ffffff">
</ngx-scrolltop>
<app-footer></app-footer>

**Comment by bartholomej** [comment]
@SovietFarmer Thank you for your feedback.

Yes, you're right. I investigated this issue and it should be fixe in version `v2.4.0-beta.1`

Can you confirm that it works, please? 

Try it here: https://ngx-scrolltop.stackblitz.io/
OR
Install beta in your project `yarn add ngx-scrolltop@beta`

Thx

**Comment by SovietFarmer** [comment]
Tested using the stackblitz, the same issue exists on iPhone 5 SE, no back to top button appears even at the bottom. I wouldn't worry about it too much though, it's such an old iOS that it's not a deal breaker.

**Comment by bartholomej** [comment]
Yes it's an old OS. A similar bug was in Internet Explorer 11 :)
It should be fixed now. Unfortunately, on iOS it's not smoothly animated, but it should fulfill its function – Scroll to top.

https://bartholomej.github.io/ngx-scrolltop/

I tried it on iOS10 and it looked good.

**Comment by SovietFarmer** [comment]
Fixed, thanks mate!
