### ISSUE TITLE
When we use span with custom css and use the background color then its appears always 

### ISSUE THREAD

**Issue by Umashankarsaw** [bartholomej/ngx-scrolltop#18]

**Comment by Umashankarsaw** [comment]
This problem comes when use the component and custom span with same class like below code
`<ngx-scrolltop
  [backgroundColor]="'#ff6700'"
  [symbolColor]="'#fafafa'"
  [size]="40"
  [mode]="'classic'"
  class="go-to-top"
  position="right"
  theme="gray">
</ngx-scrolltop>
<span ngxScrollTop class="go-to-top">
    <i class="fa fa-arrow-up" ></i> Back to top
  </span>`

**Comment by bartholomej** [comment]
Hi @Umashankarsaw  I'm not sure what you're trying to do? Are you trying to use both approaches? Directive and component?

Anyway, I noticed that you closed the issue, so I hope it's okay :)
