### ISSUE TITLE
Triggers change detection cycle on every `scroll` event

### ISSUE THREAD

**Issue by dimakuba** [bartholomej/ngx-scrolltop#32]
The package is great, but for quite complex projects it could be a performance problem 😕
<img width="1392" alt="Screenshot 2021-11-30 at 11 17 56" src="https://user-images.githubusercontent.com/14943911/144020056-3759871b-eb57-489c-a705-a2f6de4c77a4.png">

**Comment by bartholomej** [comment]
Hi @dimakuba, this has been on my todo list for quite some time. 
Thanks for reminding me and making me finally do it ;) 

See more in pull request #33 

You can install and test performance in version _v3.1.0-next.1_ like this:

```bash
npm i ngx-scrolltop@next
```

Let me know how it works ;)
