### ISSUE TITLE
[ngxScrollTopMode] is ignored

### ISSUE THREAD

**Issue by FavillaFlavia** [bartholomej/ngx-scrolltop#46]
I try to use my custom button like that:
`<span ngxScrollTop [ngxScrollTopMode]="'classic'"> TOP </span>`

But ngxScrollTopMode does't work at all, the btn is ALWAYS visible, also if the page is barely scrollable ( if I click the btn I move to the top of the page, so this works good). 
Instead, 
`<ngx-scrolltop mode="classic">↑</ngx-scrolltop>`
works perfectly.

I'm using:
    "ngx-scrolltop": "^4.1.2",
    "@angular/cdk": "^13.3.5",
    "@angular/core": "^13.3.5",

What I am doing wrong?
Thank you

**Comment by bartholomej** [comment]
@FavillaFlavia I created an example exactly according to your code and it seems to work. I only added some css.

See here:
https://stackblitz.com/edit/ngx-scrolltop-directive-test?file=src%2Fapp%2Fapp.component.html

Are you using it like this or in another way?

**Comment by FavillaFlavia** [comment]
Thank you for your super-fast reply :)
My bad, I tested your code and it worked well. 
Then I noticed that in my css there was an "display: flex" I used to align icon and text in the button, that caused the malfunction.

Again, Thank you so much for your fast reply  :)
