### ISSUE TITLE
Using CSS vars to theme color

### ISSUE THREAD

**Issue by AlonsoK28** [bartholomej/ngx-scrolltop#5]
Is possible do this?

`<ngx-scrolltop [size]="55" color="var(--dark)"></ngx-scrolltop>`

Because Ive tried but doesnt work

😉

**Comment by bartholomej** [comment]
@AlonsoK28 Great idea to use css variables directly 👍 
I beleive it is possible, but what kind of color are you trying to set?

There are some options for colors: `theme` [(docs)](https://github.com/bartholomej/ngx-scrolltop/blob/master/projects/ngx-scrolltop/src/lib/ngx-scrolltop.interface.ts), `backgroundColor`, `symbolColor`

As you can see here: https://github.com/bartholomej/ngx-scrolltop#component

Your example:
```html
<ngx-scrolltop
  [size]="55"
  backgroundColor="var(--dark)"
  symbolColor="#fff">
</ngx-scrolltop>
 ```

Let me know how was it ;)

**Comment by AlonsoK28** [comment]
Iam usgin auxilari class for [Boostrap 4 ](https://getbootstrap.com/docs/4.0/utilities/colors/) colors but doesnt works

**Comment by bartholomej** [comment]
@AlonsoK28 OK, so I realized there was a ["bug"](https://github.com/angular/angular/issues/9343) in Angular 8, but it works in Angular 9.

As you can see here:
https://stackblitz.com/edit/ngxscrolltop-cssvariables?file=src/app/app.component.html

**Comment by AlonsoK28** [comment]
Thanks a lot. I'm going to try. 😁

**Comment by AlonsoK28** [comment]
working on `ng 9` perfectly
