### ISSUE TITLE
Type '{ alias: "ngxScrollTopMode"; required: false; }' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by Mozaritta** [bartholomej/ngx-scrolltop#81]
I am getting a problem once I installed the package, I have Angular version 15, installed `ng add ngx-scrolltop@latest` but I can't solve the problem, any help?
![image](https://github.com/bartholomej/ngx-scrolltop/assets/68256290/b5f5685e-6529-4415-8286-e59ee9d731cc)

**Comment by antoprudenzano** [comment]
+1 same Angular version and same error.

**Comment by bartholomej** [comment]
Thanks for the report.  @Mozaritta @antoprudenzano 
I just tried it on a real project with angular 15 and ran the tests and everything looks fine. 
Can you show me your configuration?

This was my configuration:
`package.json`
```json
{ 
  "dependencies": {
    "@angular/core": "^15.2.5",
    "ngx-scrolltop": "^6.0.0",
  }
} 
```

I just added new module `NgxScrollTopModule` to `app.module.ts` file and used ng-scrolltop like this:

`app.component.html` (as a directive)
```html
<button
  ngxScrollTop
  ngxScrollTopMode="classic"
  class="my-custom-style"
>
  top
</button>
```

or

`app.component.html` (as a component)
```html
<ngx-scrolltop></ngx-scrolltop>
```

**Comment by somq** [comment]
Same here, `15.2.9` in my case.
Works with v4 though (`ng add ngx-scrolltop@4`)

```
Angular CLI: 15.2.9
Node: 18.16.0
Package Manager: yarn 1.22.4
OS: linux x64

Angular: 15.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@schematics/angular             15.2.9
ng-packagr                      15.2.2
rxjs                            7.8.1
typescript                      4.8.4
```

**Comment by bartholomej** [comment]
@somq Thx, and are you using directive or component? Can you show me how you use it?
