### ISSUE TITLE
Support standalone component to decrease my bundle size

### ISSUE THREAD

**Issue by Celtian** [bartholomej/ngx-scrolltop#85]
**Is your feature request related to a problem? Please describe.**
`NgxScrollTopModule` is increasing my bundle size for no reason. I just want to use `NgxScrollTopDirective` without importing `NgxScrollTopComponent`.

**Describe the solution you'd like**
Please make `NgxScrollTopDirective` & `NgxScrollTopComponent` standalone... `NgxScrollTopModule` can be still available (Same like `CommonModule` in `@angular/core`)

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by bartholomej** [comment]
This is the new pre-release of ngx-scrolltop `17.0.0-next.0`. (Yes I want to skip 10 major versions now 😀)

```
yarn add ngx-scrolltop@next
```

Setup instructions for standalone components are [here](https://github.com/bartholomej/ngx-scrolltop/tree/standalone?tab=readme-ov-file#%EF%B8%8F-setup-and-usage-standalone-or-modules) and it's easy :)
