### ISSUE TITLE
Timeline for Angular 17 Support

### ISSUE THREAD

**Issue by ericrovtar** [bartholomej/ngx-scrolltop#86]
Quick question, but I have a project we're upgrading to Angular 17 that uses this package. It's the only one that doesn't have Angular 17 support. I was wondering if there was a timeline to get that added.

Thanks!

**Comment by bartholomej** [comment]
Hi @ericrovtar,
Here you go:) Just try version `7` and let me know.

```
yarn add ngx-scrolltop@next
```

If all goes well, I'll release a stable major version. Thanks! ;)

**Comment by ericrovtar** [comment]
Hey, @bartholomej! Looks like it works. Thanks for the quick response!

**Comment by bartholomej** [comment]
Great! Version 7.0.0 has just been released.

By the way, there is a new `next` version of ngx-scrolltop `17.0.0` that will support Angular Standalone components. 
Do you use standalone components? If so, could you test it for me? @ericrovtar 

More info is here https://github.com/bartholomej/ngx-scrolltop/issues/85#issuecomment-1854810256

**Comment by ericrovtar** [comment]
@bartholomej We don't have any standalone components currently. We're making the leap from 13 to 17, so those just became available for us, otherwise, I'd definitely test them.

**Comment by bartholomej** [comment]
Yeah, thanks anyway. Someone else will try it ;)
